# Generated by Django 3.2.19 on 2023-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_auto_20230809_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='Aadhar',
            field=models.BigIntegerField(null=True),
        ),
    ]
