# Generated by Django 3.2.19 on 2023-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_alter_payroll_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='Aadhar',
            field=models.CharField(default=111122224444, max_length=250),
            preserve_default=False,
        ),
    ]
